create table if not exists public."USUARIOS" (
  id bigint generated by default as identity primary key,
  nome_usuario text not null,
  tipo_usuario integer not null,
  senha_usuario text not null
);

create table if not exists public."CATEGORIA" (
  id bigint generated by default as identity primary key,
  nome_categoria text not null
);

create table if not exists public."LOCAL_ESTOQUE" (
  id bigint generated by default as identity primary key,
  nome_local text not null
);


create table if not exists public."FORNECEDOR" (
  id bigint generated by default as identity primary key,
  nome_fornecedor text not null
);

create table if not exists public."PRODUTOS" (
  id bigint generated by default as identity primary key,
  nome_produto text not null,
  custo_produto_Unit numeric(10,2) not null,
  valor_venda_Unit numeric(10,2) not null,
  id_local bigint not null references public."LOCAL_ESTOQUE"(id),
  id_categoria bigint not null references public."CATEGORIA"(id),
  id_fornecedor bigint not null references public."FORNECEDOR"(id),
  quantidade integer not null default 0,
  estoque_minimo integer not null default 0
);

-- Tabela de VENDAS
create table if not exists public."VENDAS" (
  id bigint generated by default as identity primary key,
  data_venda timestamp with time zone default now() not null,
  id_usuario bigint not null references public."USUARIOS"(id)
);

-- Tabela de ITENS_VENDA (N:N entre VENDAS e PRODUTOS)
create table if not exists public."ITENS_VENDA" (
  id bigint generated by default as identity primary key,
  id_venda bigint not null references public."VENDAS"(id) on delete cascade,
  id_produto bigint not null references public."PRODUTOS"(id),
  quantidade integer not null check (quantidade > 0),
  valor_unitario numeric(10,2) not null
);