create table if not exists public."USUARIOS" (
  id bigint generated by default as identity primary key,
  nome_usuario text not null,
  tipo_usuario integer not null,
  senha_usuario text not null
);

create table if not exists public."CATEGORIA" (
  id bigint generated by default as identity primary key,
  nome_categoria text not null
);

create table if not exists public."LOCAL_ESTOQUE" (
  id bigint generated by default as identity primary key,
  nome_local text not null
);


create table if not exists public."FORNECEDOR" (
  id bigint generated by default as identity primary key,
  nome_fornecedor text not null
);

create table if not exists public."PRODUTOS" (
  id bigint generated by default as identity primary key,
  nome_produto text not null,
  custo_produto_Unit numeric(10,2) not null,
  valor_venda_Unit numeric(10,2) not null,
  id_local bigint not null references public."LOCAL_ESTOQUE"(id),
  id_categoria bigint not null references public."CATEGORIA"(id),
  id_fornecedor bigint not null references public."FORNECEDOR"(id),
  quantidade integer not null default 0,
  estoque_minimo integer not null default 0
);

CREATE TABLE IF NOT EXISTS public."MOVIMENTO_ESTOQUE" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_produto BIGINT NOT NULL REFERENCES public."PRODUTOS"(id),
  id_usuario BIGINT NOT NULL REFERENCES public."USUARIOS"(id),
  tipo_movimento VARCHAR(10) NOT NULL CHECK (tipo_movimento IN ('ENTRADA', 'SAIDA')),
  quantidade INTEGER NOT NULL CHECK (quantidade > 0),
  data_movimento TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);